[DCOS-46239] Add warning for docker.user on RHEL/CentOS platform (#465)
* Add warning for docker.user on RHEL/CentOS platform

When deploying Spark with default configurations from 2.5.0-2.2.1
(ie user=nobody) on RHEL/CentOS, the service will fail to create the
required directories due to user ID mismatch.

This commit adds an error message that helps with debugging such an
issue.

diff --git a/docker/runit/service/spark/log/run b/docker/runit/service/spark/log/run
--- a/docker/runit/service/spark/log/run
+++ b/docker/runit/service/spark/log/run
@@ -2,6 +2,9 @@
 set -e
 set -x
 
-mkdir -p "${MESOS_SANDBOX}"/spark
+mkdir -p "${MESOS_SANDBOX}"/spark || {
+    echo "ERROR: User '$(whoami)' does not have sufficient permissions to create the /spark directory in ${MESOS_SANDBOX}" >&2
+    echo "- if deploying Spark using the Docker engine on RHEL/CentOS, please set 'docker.user' to the correct UID. For user 'nobody', the UID is 99" >&2
+    echo "- see https://docs.mesosphere.com/services/spark/latest/limitations for more details" >&2
+}
 exec svlogd "${MESOS_SANDBOX}"/spark
-
